"""Initial commit

Revision ID: 2d2df28d87b1
Revises: 
Create Date: 2025-10-07 20:04:19.239158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2df28d87b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_mechanics',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('total_gold', sa.Integer(), nullable=False),
    sa.Column('lives', sa.Integer(), nullable=False),
    sa.Column('rounds_played', sa.Integer(), nullable=False),
    sa.Column('best_round_gold', sa.Integer(), nullable=False),
    sa.Column('last_round_played_at', sa.DateTime(), nullable=True),
    sa.Column('daily_bonus_step', sa.Integer(), nullable=False),
    sa.Column('daily_bonus_last_taken_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('referral_master_id', sa.BigInteger(), nullable=False),
    sa.Column('referral_user_id', sa.BigInteger(), nullable=False),
    sa.Column('referral_gain_gold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referral_master_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referral_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referrals')
    op.drop_table('game_mechanics')
    op.drop_table('users')
    # ### end Alembic commands ###
